product:
  name: Red Hat Integration
  abbreviation: RHI
  stage: ${WORKSPACE}
  issueTrackerUrl: http://issues.jboss.org/browse/ENTESB
version: 1.0.0
milestone: DR1
group: Red Hat Integration - Service Registry 1.0.0 DR2
defaultBuildParameters:
  environmentId: 8  

builds:
- name: apicurio-registry-1.0.0-DR2
    #fetchScmUrl: 1
    #pushScmUrl: 1
    #tag: apicurio-registry-${version.apicurito-registry}
    #buildCommand: 1
  project: redhat-integration/apicurio-registry
  scmUrl: git+ssh://code.engineering.redhat.com/redhat-integration/apicurio-registry.git
  externalScmUrl: git@github.com/redhat-integration/apicurio-registry.git
  scmRevision: paolo2
  buildScript: >
   export REG="http://indy.newcastle.svc.cluster.local/api/folo/track/${buildContentId}/npm/remote/yarnpkg/"
   sed -i "s#https://registry.npmjs.org/#${REG}#g" ui/yarn.lock
   sed -i "s#https://registry.yarnpkg.com/#${REG}#g" ui/yarn.lock
   sed -i 's#https:#http:#g' ui/yarn.lock
   mvn -B clean deploy \
       -Dmaven.test.skip=true \
       -DskipTests \
       -Dtar.long.file.mode=posix \
       -Dproxy-server=$REG \
       -Dcustom-registry=$REG \
       -DnpmRegistryURL2=$REG \
       -Dyarn-insecure \
       -DnpmDownloadRoot=http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/fuse/npm/dist/npm/ \
       -DyarnRegistry=$REG \
       -Dproxy-user="${buildContentId}+tracking" \
       -Dproxy-password="${accessToken}" \
       -Dproxy-port="${proxyPort}" \
       -DyarnDownloadRoot=http://rcm-guest.app.eng.bos.redhat.com/rcm-guest/staging/fuse/service-registry/yarn/ \
       -DnodeDownloadRoot=http://rcm-guest.app.eng.bos.redhat.com/rcm-guest/staging/fuse/service-registry/node/ \
       -Pprod \
       -Pkafka \
       -Pjpa \
       -Pwith-proxy \
       -Pwith-custom-registry \
       -Pverbose
  customPmeParameters:
    - -DgroovyScripts=https://gitlab.cee.redhat.com/pantinor/build-configurations/raw/ipt/ipt/service_registry/1.0.0/MangleDependencies.groovy
    - -DpluginSource=NONE

outputPrefixes:
  releaseFile: redhat-integration
  releaseDir: redhat-integration
flow:
  #licensesGeneration: gen.downloadFrom 'karaf' matching '.*license\.zip'
  #licensesGeneration: gen.generate()
  #repositoryGeneration: gen.downloadFrom 'karaf' matching '.*-m2repo\.zip'
  #javadocGeneration: gen.downloadFrom 'karaf' matching '.*javadoc\.zip'
  #addons:
  #runtimeDependenciesAnalyzer:
  #  downloadFrom: 'WildFly-Swarm'
  #  matching: '.*runtime-dependencies\.zip'
  #  referenceBuild: 'WildFly-Swarm'
