name: quarkus Workflow
on: workflow_dispatch

jobs:
  test-push:
    name: Test
    runs-on: ubuntu-18.04    
    steps:
        
      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64
      
      - name: Build Quarkus
        run: git clone https://github.com/quarkusio/quarkus.git && cd quarkus && mvn -B clean install -DskipTests -DskipITs
        
      - name: Clone Registry
        run: git clone https://github.com/Apicurio/apicurio-registry.git
        
      - name: Build Registry
        run: cd apicurio-registry && ./mvnw -Pprod -Psql -Pstreams -Pasyncmem -Pkafkasql -Pinfinispan test package -Dquarkus.version=999-SNAPSHOT
        
      - name: Integration Tests
        run: cd apicurio-registry && ./mvnw verify -Pall -pl tests -Dmaven.javadoc.skip=true -Dquarkus.version=999-SNAPSHOT
