name: Nightly Build # nightly job to run against Quarkus master so the issues are detected early.
on: 
  workflow_dispatch: {}

jobs:
  test-push:
    name: Test
    runs-on: ubuntu-18.04 
    steps:
    
        
        - name: Checkout Code with Ref '${GITHUB_REF##*/}' 
          uses: actions/checkout@v2
            
        - name: Set up JDK 11
          run: |
            chmod 777 .github/scripts/test.sh
            ./.github/scripts/test.sh ${GITHUB_REF##*/}
