name: Post-Release # nightly job to run against Quarkus master so the issues are detected early.
on:
  release:
    types: [published]

jobs:
  test-push:
    name: Test
    runs-on: ubuntu-18.04 
    steps:
    
        - name: Print Message
          run: echo "Hello"
