name: Post-Release 
on:
  release:
    types: [released]

jobs:
  test-push:
    name: Test
    runs-on: ubuntu-18.04 
    steps:
    
        - name: Print Github Event Context
          run: echo ${{ github.event }}
