name: Post-Release 
on:
  release:
    types: [released]
env:
  RELEASE_VERSION: ${{ github.event.release.name }}
  SOURCE_CODE_URL: ${{ github.event.release.zipball_url }}
  BRANCH: ${{ github.event.release.target_commitish }}

jobs:
  Dump-Context:
    runs-on: ubuntu-18.04 
    steps:
    
      - name: Dump GitHub Release Event context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event.release) }}
        run: echo "$GITHUB_CONTEXT"
        
  Test:
    runs-on: ubuntu-18.04 
    steps:
    
      - name: Determine Floating Tag
        run: |
          if [[ $BRANCH == 'master' ]]
          then
              echo "FLOATING_TAG=latest-release" >> $GITHUB_ENV
          else
              echo "FLOATING_TAG=$BRANCH-release" >> $GITHUB_ENV
          fi
          
      - name: Print Environment Variables
        run: |
          echo $${{env.RELEASE_VERSION}}
          echo $${{env.SOURCE_CODE_URL}}
          echo $${{env.BRANCH}}
          echo $${{env.FLOATING_TAG}}
