name: Registry Test Build
on: workflow_dispatch

jobs:
    test:
        name: Test
        runs-on: ubuntu-18.04    
        steps:
            
        - name: Set up JDK 11
          uses: AdoptOpenJDK/install-jdk@v1
          with:
            version: '11'
            architecture: x64

        - name: Set test profile to all
          run: |
            echo "test_profile=all" >> $GITHUB_ENV
            
        - name: Clone Registry
          run: git clone https://github.com/Apicurio/apicurio-registry.git
                
        - name: Checkout `create-bom` branch
          run: cd apicurio-registry && git checkout create-bom
            
        - name: Get maven wrapper
          run: cd apicurio-registry && mvn -N io.takari:maven:wrapper -Dmaven=3.6.3

        - name: Build Registry - multitenacy
          run: cd apicurio-registry && ./mvnw clean install -Pprod -Pmultitenancy
            
        - name: Build Registry - asyncmem
          run: cd apicurio-registry && ./mvnw install -Pprod -Pasyncmem

        - name: Build Registry - infinispan
          run: cd apicurio-registry && ./mvnw install -Pprod -Pinfinispan

        - name: Build Registry - sql
          run: cd apicurio-registry && ./mvnw install -Pprod -Psql

        - name: Build Registry - streams
          run: cd apicurio-registry && ./mvnw install -Pprod -Pstreams

        - name: Build Registry - kafkasql
          run: cd apicurio-registry && ./mvnw install -Pprod -Pkafkasql

        - name: Build integration-tests-common
          run: cd apicurio-registry && mvn install -Pintegration-tests -pl integration-tests/integration-tests-common

        - name: Run Integration Tests - streams
          run: cd apicurio-registry && ./mvnw verify -Pintegration-tests -P${{ env.test_profile }} -Pstreams -pl integration-tests/testsuite -Dmaven.javadoc.skip=true --no-transfer-progress

        - name: Run Integration Tests - sql
          run: cd apicurio-registry && ./mvnw verify -Pintegration-tests -P${{ env.test_profile }} -Psql -pl integration-tests/testsuite -Dmaven.javadoc.skip=true --no-transfer-progress

        - name: Run Integration Tests - infinispan
          run: cd apicurio-registry && ./mvnw verify -Pintegration-tests -P${{ env.test_profile }} -Pinfinispan -pl integration-tests/testsuite -Dmaven.javadoc.skip=true --no-transfer-progress

        - name: Run Integration Tests - kafkasql
          run: cd apicurio-registry && ./mvnw verify -Pintegration-tests -P${{ env.test_profile }} -Pkafkasql -pl integration-tests/testsuite -Dmaven.javadoc.skip=true --no-transfer-progress

        - name: Run Integration Tests - multitenancy
          run: cd apicurio-registry && ./mvnw verify -Pintegration-tests -Pmultitenancy -Psql -pl integration-tests/testsuite -Dmaven.javadoc.skip=true --no-transfer-progress -DtrimStackTrace=false 

        - name: Run Legacy Tests - streams
          run: cd apicurio-registry && ./mvnw verify -Pintegration-tests -P${{ env.test_profile }} -Pstreams -pl integration-tests/legacy-tests -Dmaven.javadoc.skip=true --no-transfer-progress
            
        - name: Run Legacy Tests - sql
          run: cd apicurio-registry && ./mvnw verify -Pintegration-tests -P${{ env.test_profile }} -Psql -pl integration-tests/legacy-tests -Dmaven.javadoc.skip=true --no-transfer-progress
