name: Release Image
on:
  workflow_dispatch: {}
  release:
    types: [released]

jobs:
  release-images:
    runs-on: ubuntu-18.04 
    steps:

      - name: Download Source Code
        run: git clone https://github.com/riprasad/registry-test.git registry

      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: Build Project
        run: cd registry && ./mvnw clean install -DskipTests=true

      - name: Build The Images For Docker.io
        run: |
          cd registry
          docker build -f ./distro/docker/target/docker/Dockerfile.jvm -t docker.io/riprasad/apicurio-registry-mem:latest ./distro/docker/target/docker 

      - name: List All Docker Images
        run: docker images
      
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u "riprasad" --password-stdin
          
      - name: Push The Images To Docker.io 
        run: |
          cd registry
          docker push docker.io/riprasad/apicurio-registry-mem:latest
        
      - name: Build The Images For Quay.io
        run: |
          cd registry
          docker build -f ./distro/docker/target/docker/Dockerfile.jvm -t quay.io/riprasad/apicurio-registry-mem:latest ./distro/docker/target/docker 

      - name: List All Docker Images
        run: docker images
          
      - name: Login to Quay.io Registry
        run: docker login -u "riprasad" -p "${{ secrets.QUAY_PASSWORD }}" Quay.io
          
      - name: Push The Images To Quay.io 
        run: |
          cd registry
          docker push quay.io/riprasad/apicurio-registry-mem:latest