name: Release Workflow
on:
  pull_request:
    branches: [master]
    types: [closed]
    paths:
      - '.github/project.yaml'

jobs:
  release:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true
    steps:
      - name: Retrieve Project Metadata
        uses: radcortez/project-metadata-action@master
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yaml'
      - name: Echo
        run: echo "TESTING"

  verify-release:
    runs-on: ubuntu-18.04
    needs: ["release"]
    if: github.event.pull_request.merged == true
    steps:
      - name: Retrieve Project Metadata
        uses: radcortez/project-metadata-action@master
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yaml'
      - name: Set up JDK 1.8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
            version: '8'
            architecture: x64
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Verify Docker Release
        run: ./.github/scripts/verify-docker-release.sh
      - name: Verify Maven Release
        run: |
          cd .github/test-mvn-deploy
          mvn clean install "-Dversion.apicurio=${{steps.metadata.outputs.release-version}}"
