name: Release Workflow
on:
  workflow_dispatch:
    inputs:      
      release-version:
        description: 'Version being released'
        required: true
      branch:
        description: 'Branch to release from'
        required: true
        default: 'master'
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set up JDK 1.8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
            version: '8'
            architecture: x64
      - name: Apicurio Registry Checkout
        run: |
          mkdir registry
          cd registry
          git init
          git config --global user.name "apicurio-ci"
          git config --global user.email "apicurio.ci@gmail.com"
          git remote add origin "https://github.com/Apicurio/apicurio-registry.git"
          git fetch
          git pull origin master
      - name: Build Registry (All Variants)
        run: |
          cd registry
          mvn clean install -Pprod -Psql -Pinfinispan -Pstreams -Pasyncmem -Pkafkasql -DskipTests
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build The Tagged Docker Images
        run: |
          cd registry/distro/docker
          mvn package -Pprod -DskipTests -Ddocker -Ddocker.tag.name=latest-snapshot
          mvn package -Pprod -Psql -DskipTests -Ddocker -Ddocker.tag.name=latest-snapshot
          mvn package -Pprod -Pinfinispan -DskipTests -Ddocker -Ddocker.tag.name=latest-snapshot
          mvn package -Pprod -Pstreams -DskipTests -Ddocker -Ddocker.tag.name=latest-snapshot
          mvn package -Pprod -Pasyncmem -DskipTests -Ddocker -Ddocker.tag.name=latest-snapshot
          mvn package -Pprod -Pkafkasql -DskipTests -Ddocker -Ddocker.tag.name=latest-snapshot
          
      - name: List Docker Images
        run: docker images
      
      - name: Tag Docker Images for dokerhub
        run: |
          docker image tag apicurio/apicurio-registry-mem:latest-snapshot riprasad/apicurio-registry-mem:latest-snapshot
          docker image tag apicurio/apicurio-registry-sql:latest-snapshot riprasad/apicurio-registry-sql:latest-snapshot
          docker image tag apicurio/apicurio-registry-infinispan:latest-snapshot riprasad/apicurio-registry-infinispan:latest-snapshot
          docker image tag apicurio/apicurio-registry-streams:latest-snapshot riprasad/apicurio-registry-streams:latest-snapshot
          docker image tag apicurio/apicurio-registry-asyncmem:latest-snapshot riprasad/apicurio-registry-asyncmem:latest-snapshot
          docker image tag apicurio/apicurio-registry-kafkasql:latest-snapshot riprasad/apicurio-registry-kafkasql:latest-snapshot
          
      - name: List Docker Images
        run: docker images
        
      - name: Push The Tagged Docker Images to Dockerhub
        run: |
          docker push riprasad/apicurio-registry-mem:latest-snapshot
          docker push riprasad/apicurio-registry-sql:latest-snapshot
          docker push riprasad/apicurio-registry-infinispan:latest-snapshot
          docker push riprasad/apicurio-registry-streams:latest-snapshot
          docker push riprasad/apicurio-registry-asyncmem:latest-snapshot
          docker push riprasad/apicurio-registry-kafkasql:latest-snapshot
          
      - name: Login to Quay.io Registry
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
        
      - name: Tag Docker Images for Quay.io
        run: |
          docker image tag apicurio/apicurio-registry-mem:latest-snapshot quay.io/riprasad/apicurio-registry-mem:latest-snapshot
          docker image tag apicurio/apicurio-registry-sql:latest-snapshot quay.io/riprasad/apicurio-registry-sql:latest-snapshot
          docker image tag apicurio/apicurio-registry-infinispan:latest-snapshot quay.io/riprasad/apicurio-registry-infinispan:latest-snapshot
          docker image tag apicurio/apicurio-registry-streams:latest-snapshot quay.io/riprasad/apicurio-registry-streams:latest-snapshot
          docker image tag apicurio/apicurio-registry-asyncmem:latest-snapshot quay.io/riprasad/apicurio-registry-asyncmem:latest-snapshot
          docker image tag apicurio/apicurio-registry-kafkasql:latest-snapshot quay.io/riprasad/apicurio-registry-kafkasql:latest-snapshot
          
      - name: List Docker Images
        run: docker images
        
      - name: Push The Tagged Docker Images to Quay.io
        run: |  
          docker push quay.io/riprasad/apicurio-registry-mem:latest-snapshot
          docker push quay.io/riprasad/apicurio-registry-sql:latest-snapshot
          docker push quay.io/riprasad/apicurio-registry-infinispan:latest-snapshot
          docker push quay.io/riprasad/apicurio-registry-streams:latest-snapshot
          docker push quay.io/riprasad/apicurio-registry-asyncmem:latest-snapshot
          docker push quay.io/riprasad/apicurio-registry-kafkasql:latest-snapshot
