name: Release Images
on:
  workflow_dispatch: {}
  release:
    types: [released]

jobs:
  release-images:
    runs-on: ubuntu-18.04 
    steps:

      - name: Download Source Code
        run: git clone https://github.com/riprasad/registry-test.git registry

      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: Build Project
        run: cd registry && make SKIP_TESTS=true BUILD_FLAGS='-Dmaven.wagon.httpconnectionManager.maxTotal=30 -Dmaven.wagon.http.retryHandler.count=5' build-all

      - name: Build The Images For Docker.io
        run: cd registry && ./.github/scripts/build-images.sh master docker.io release ${RELEASE_VERSION} 

      - name: List All Docker Images
        run: docker images
      
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u "riprasad" --password-stdin
          
      - name: Push The Images To Docker.io 
        run: cd registry && ./.github/scripts/push-images.sh master docker.io release ${RELEASE_VERSION}
        
      - name: Build The Images For Quay.io
        run: cd registry && ./.github/scripts/build-images.sh master quay.io release ${RELEASE_VERSION}

      - name: List All Docker Images
        run: docker images
          
      - name: Login to Quay.io Registry
        run: docker login -u "riprasad" -p "${{ secrets.QUAY_PASSWORD }}" Quay.io
          
      - name: Push The Images To Quay.io 
        run: cd registry && ./.github/scripts/push-images.sh master quay.io release ${RELEASE_VERSION}