name: Release Workflow
on:
  workflow_dispatch:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'master'
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set up JDK 1.8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
            version: '8'
            architecture: x64
      - name: Apicurio Registry Checkout
        run: |
          mkdir registry
          cd registry
          git init
          git config --global user.name "apicurio-ci"
          git config --global user.email "apicurio.ci@gmail.com"
          git remote add origin "https://github.com/Apicurio/apicurio-registry.git"
          git fetch
          git pull
      - name: Build Registry (All Variants)
        run: |
          cd registry
          mvn clean install -Pprod -Psql -Pinfinispan -Pstreams -Pasyncmem -DskipTests
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build The Tagged Docker Images
        run: |
          cd registry/distro/docker
          mvn package -Pprod -DskipTests -Ddocker
          mvn package -Pprod -Psql -DskipTests -Ddocker
          mvn package -Pprod -Pinfinispan -DskipTests -Ddocker
          mvn package -Pprod -Pstreams -DskipTests -Ddocker
          mvn package -Pprod -Pasyncmem -DskipTests -Ddocker
      - name: Tag Docker Images for dokerhub
        run: |
          cd registry
          docker image tag apicurio/apicurio-registry-mem:latest riprasad/apicurio/apicurio-registry-mem:latest
          docker image tag apicurio/apicurio-registry-mem:latest-release riprasad/apicurio/apicurio-registry-mem:latest-release
          docker image tag apicurio/apicurio-registry-mem:${{ github.event.inputs.release-version}} riprasad/apicurio/apicurio-registry-mem:${{ github.event.inputs.release-version}}
          docker image tag apicurio/apicurio-registry-sql:latest riprasad/apicurio/apicurio-registry-sql:latest
          docker image tag apicurio/apicurio-registry-sql:latest-release riprasad/apicurio/apicurio-registry-sql:latest-release
          docker image tag apicurio/apicurio-registry-sql:${{ github.event.inputs.release-version}} riprasad/apicurio/apicurio-registry-sql:${{ github.event.inputs.release-version}}
          docker image tag apicurio/apicurio-registry-infinispan:latest riprasad/apicurio/apicurio-registry-infinispan:latest
          docker image tag apicurio/apicurio-registry-infinispan:latest-release riprasad/apicurio/apicurio-registry-infinispan:latest-release
          docker image tag apicurio/apicurio-registry-infinispan:${{ github.event.inputs.release-version}} riprasad/apicurio/apicurio-registry-infinispan:${{ github.event.inputs.release-version}}
          docker image tag apicurio/apicurio-registry-streams:latest riprasad/apicurio/apicurio-registry-streams:latest
          docker image tag apicurio/apicurio-registry-streams:latest-release riprasad/apicurio/apicurio-registry-streams:latest-release
          docker image tag apicurio/apicurio-registry-streams:${{ github.event.inputs.release-version}} riprasad/apicurio/apicurio-registry-streams:${{ github.event.inputs.release-version}}
          docker image tag apicurio/apicurio-registry-asyncmem:latest riprasad/apicurio/apicurio-registry-asyncmem:latest
          docker image tag apicurio/apicurio-registry-asyncmem:latest-release riprasad/apicurio/apicurio-registry-asyncmem:latest-release
          docker image tag apicurio/apicurio-registry-asyncmem:${{ github.event.inputs.release-version}} riprasad/apicurio/apicurio-registry-asyncmem:${{ github.event.inputs.release-version}}
      - name: Push The Tagged Docker Images to Dockerhub
        run: |
          cd registry
          docker push riprasad/apicurio/apicurio-registry-mem:latest
          docker push riprasad/apicurio/apicurio-registry-mem:latest-release
          docker push riprasad/apicurio/apicurio-registry-mem:${{ github.event.inputs.release-version}}
          docker push riprasad/apicurio/apicurio-registry-sql:latest
          docker push riprasad/apicurio/apicurio-registry-sql:latest-release
          docker push riprasad/apicurio/apicurio-registry-sql:${{ github.event.inputs.release-version}}
          docker push riprasad/apicurio/apicurio-registry-infinispan:latest
          docker push riprasad/apicurio/apicurio-registry-infinispan:latest-release
          docker push riprasad/apicurio/apicurio-registry-infinispan:${{ github.event.inputs.release-version}}
          docker push riprasad/apicurio/apicurio-registry-streams:latest
          docker push riprasad/apicurio/apicurio-registry-streams:latest-release
          docker push riprasad/apicurio/apicurio-registry-streams:${{ github.event.inputs.release-version}}
          docker push riprasad/apicurio/apicurio-registry-asyncmem:latest
          docker push riprasad/apicurio/apicurio-registry-asyncmem:latest-release
          docker push riprasad/apicurio/apicurio-registry-asyncmem:${{ github.event.inputs.release-version}}
      - name: Tag Docker Images for Quay.io
        run: |
          cd registry
          docker image tag apicurio/apicurio-registry-mem:latest quay.io/riprasad/apicurio/apicurio-registry-mem:latest
          docker image tag apicurio/apicurio-registry-mem:latest-release quay.io/riprasad/apicurio/apicurio-registry-mem:latest-release
          docker image tag apicurio/apicurio-registry-mem:${{ github.event.inputs.release-version}} quay.io/riprasad/apicurio/apicurio-registry-mem:${{ github.event.inputs.release-version}}
          docker image tag apicurio/apicurio-registry-sql:latest quay.io/riprasad/apicurio/apicurio-registry-sql:latest
          docker image tag apicurio/apicurio-registry-sql:latest-release quay.io/riprasad/apicurio/apicurio-registry-sql:latest-release
          docker image tag apicurio/apicurio-registry-sql:${{ github.event.inputs.release-version}} quay.io/riprasad/apicurio/apicurio-registry-sql:${{ github.event.inputs.release-version}}
          docker image tag apicurio/apicurio-registry-infinispan:latest quay.io/riprasad/apicurio/apicurio-registry-infinispan:latest
          docker image tag apicurio/apicurio-registry-infinispan:latest-release quay.io/riprasad/apicurio/apicurio-registry-infinispan:latest-release
          docker image tag apicurio/apicurio-registry-infinispan:${{ github.event.inputs.release-version}} quay.io/riprasad/apicurio/apicurio-registry-infinispan:${{ github.event.inputs.release-version}}
          docker image tag apicurio/apicurio-registry-streams:latest quay.io/riprasad/apicurio/apicurio-registry-streams:latest
          docker image tag apicurio/apicurio-registry-streams:latest-release quay.io/riprasad/apicurio/apicurio-registry-streams:latest-release
          docker image tag apicurio/apicurio-registry-streams:${{ github.event.inputs.release-version}} quay.io/riprasad/apicurio/apicurio-registry-streams:${{ github.event.inputs.release-version}}
          docker image tag apicurio/apicurio-registry-asyncmem:latest quay.io/riprasad/apicurio/apicurio-registry-asyncmem:latest
          docker image tag apicurio/apicurio-registry-asyncmem:latest-release quay.io/riprasad/apicurio/apicurio-registry-asyncmem:latest-release
          docker image tag apicurio/apicurio-registry-asyncmem:${{ github.event.inputs.release-version}} quay.io/riprasad/apicurio/apicurio-registry-asyncmem:${{ github.event.inputs.release-version}}
      - name: Login to Quay.io Registry
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
      - name: Push The Tagged Docker Images to Quay.io
        run: |
          cd registry
          docker push quay.io/riprasad/apicurio/apicurio-registry-mem:latest
          docker push quay.io/riprasad/apicurio/apicurio-registry-mem:latest-release
          docker push quay.io/riprasad/apicurio/apicurio-registry-mem:${{ github.event.inputs.release-version}}
          docker push quay.io/riprasad/apicurio/apicurio-registry-sql:latest
          docker push quay.io/riprasad/apicurio/apicurio-registry-sql:latest-release
          docker push quay.io/riprasad/apicurio/apicurio-registry-sql:${{ github.event.inputs.release-version}}
          docker push quay.io/riprasad/apicurio/apicurio-registry-infinispan:latest
          docker push quay.io/riprasad/apicurio/apicurio-registry-infinispan:latest-release
          docker push quay.io/riprasad/apicurio/apicurio-registry-infinispan:${{ github.event.inputs.release-version}}
          docker push quay.io/riprasad/apicurio/apicurio-registry-streams:latest
          docker push quay.io/riprasad/apicurio/apicurio-registry-streams:latest-release
          docker push quay.io/riprasad/apicurio/apicurio-registry-streams:${{ github.event.inputs.release-version}}
          docker push quay.io/riprasad/apicurio/apicurio-registry-asyncmem:latest
          docker push quay.io/riprasad/apicurio/apicurio-registry-asyncmem:latest-release
          docker push quay.io/riprasad/apicurio/apicurio-registry-asyncmem:${{ github.event.inputs.release-version}}
