name: Release Workflow
on:
  workflow_dispatch:
    inputs:      
      release-version:
        description: 'Version being released'
        required: true
      branch:
        description: 'Branch to release from'
        required: true
        default: 'master'
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set up JDK 1.8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
            version: '8'
            architecture: x64
      - name: Apicurio Registry Checkout
        run: |
          mkdir registry
          cd registry
          git init
          git config --global user.name "apicurio-ci"
          git config --global user.email "apicurio.ci@gmail.com"
          git remote add origin "https://github.com/Apicurio/apicurio-registry.git"
          git fetch
          git checkout ${{ github.event.inputs.branch}}
          git branch --set-upstream-to=origin/${{ github.event.inputs.branch}}
          git pull
      - name: Build Registry (All Variants)
        run: |
          cd registry
          mvn clean install -Pprod -Psql -Pinfinispan -Pstreams -Pasyncmem -Pkafkasql -DskipTests
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build The Tagged Docker Images
        run: ./.github/scripts/build-release-images-for-docker.sh ${{ github.event.inputs.branch }}
          
      - name: List Docker Images
        run: docker images
      
      - name: Tag Docker Images for dokerhub
        run: ./.github/scripts/tag-release-images-for-docker.sh ${{ github.event.inputs.branch }} ${{ github.event.inputs.release-version}}
          
      - name: List Docker Images
        run: docker images
        
      - name: Push The Tagged Docker Images to Dockerhub
        run: ./.github/scripts/push-release-images-to-docker.sh ${{ github.event.inputs.branch }} ${{ github.event.inputs.release-version}}
          
      - name: Login to Quay.io Registry
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
        
      - name: Tag Docker Images for Quay.io
        run: ./.github/scripts/tag-release-images-for-quay.sh ${{ github.event.inputs.branch }} ${{ github.event.inputs.release-version}}
          
      - name: List Docker Images
        run: docker images
        
      - name: Push The Tagged Docker Images to Quay.io
        run: ./.github/scripts/push-release-images-to-quay.sh ${{ github.event.inputs.branch }} ${{ github.event.inputs.release-version}}
