name: Syntax Test

on:
  workflow_dispatch: {}
  

jobs:
  build-linux-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch required Details
      run: |
          touch latestRelease.json && curl https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest > latestRelease.json
          echo "RELEASE_VERSION=$(cat latestRelease.json | jq -r '.name')" >> $GITHUB_ENV
          echo "SOURCE_CODE_URL=$(cat latestRelease.json | jq -r '.zipball_url')" >> $GITHUB_ENV
          echo "UPLOAD_URL=$(cat latestRelease.json | jq -r '.upload_url')" >> $GITHUB_ENV
    
    - name: Log Environment Variables
      run: |
        echo "$RELEASE_VERSION"
        echo "$SOURCE_CODE_URL"
        echo "$UPLOAD_URL"
