name: syntax-test

on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      release-linux-cli:
        required: true
        default: 'true'
      release-macos-cli:
        required: true
        default: 'true'
      release-win64-cli:
        required: true
        default: 'true'
  

jobs:
  job1:
    if: github.repository_owner == 'riprasad' && (github.event_name == 'release' || github.event.inputs.release-linux-cli)
    runs-on: ubuntu-latest
    steps:
    - name: Fetch required Details
      run: echo "Job1"

  job2:
    if: github.repository_owner == 'riprasad' && (github.event_name == 'release' || github.event.inputs.release-macos-cli)
    runs-on: ubuntu-latest
    steps:
    - name: Fetch required Details
      run: echo "Job2"

  job3:
    if: github.repository_owner == 'riprasad' && (github.event_name == 'release' || github.event.inputs.release-win64-cli)
    runs-on: ubuntu-latest
    steps:
    - name: Fetch required Details
      run: echo "Job3"
