name: syntax-test

on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      release-linux-cli:
        required: true
        default: 'true'
      release-macos-cli:
        required: true
        default: 'true'
      release-win64-cli:
        required: true
        default: 'true'
  

jobs:
  job1:
    if: github.repository_owner == 'riprasad' && (github.event_name == 'release' || github.event.inputs.release-linux-cli == 'true')
    runs-on: ubuntu-latest
    steps:
    - name: Job1
      run: |
        echo ${{ github.event_name }}
        echo ${{ github.repository_owner }}
        echo ${{ github.event.inputs.release-linux-cli }}

  job2:
    if: github.repository_owner == 'riprasad' && (github.event_name == 'release' || github.event.inputs.release-macos-cli == 'true')
    runs-on: ubuntu-latest
    steps:
    - name: Job2
      run: |
        echo ${{ github.event_name }}
        echo ${{ github.repository_owner }}
        echo ${{ github.event.inputs.release-linux-cli }}

  job3:
    if: github.repository_owner == 'riprasad' && (github.event_name == 'release' || github.event.inputs.release-win64-cli == 'true')
    runs-on: ubuntu-latest
    steps:
    - name: Job3
      run: |
        echo ${{ github.event_name }}
        echo ${{ github.repository_owner }}
        echo ${{ github.event.inputs.release-linux-cli }}
