name: Test Job
on:
  workflow_dispatch: {}

jobs:
  joba:
    runs-on: ubuntu-18.04 
    steps:

      - name: Fetch Latest Release Details
        run: touch latestRelease.json && curl https://api.github.com/repos/apicurio/apicurio-registry/releases/latest > latestRelease.json

      - name: Retrieve Required Details
        run: |
          echo "RELEASE_VERSION=$(cat latestRelease.json | jq '.name' | sed 's/"//g')" >> $GITHUB_ENV
          echo "SOURCE_CODE_URL=$(cat latestRelease.json | jq '.zipball_url' | sed 's/"//g')" >> $GITHUB_ENV

      - name: Download Source Code
        run: wget -c $SOURCE_CODE_URL && unzip $RELEASE_VERSION && ls -lrt && mv Apicurio* registry

      - name: view files
        run: ls -lrt


  jobb:
    runs-on: ubuntu-18.04
    needs: ["joba"]
    steps:

      - name: view files
        run: ls -lrt
         
      - name: print env variable
        run: |
           echo ${{env.RELEASE_VERSION}}
           echo ${{env.SOURCE_CODE_URL}}
