name: Test Workflow
on:
  push:
    branches: [test-234]

jobs:
  test-push:
    name: Verify Build
    runs-on: ubuntu-18.04    
    steps:
      - name: Print Branch
        run: |
          echo "${{ github.ref }}"

      - name: Checkout Code With Branch ${{ github.ref[11:] }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: list directory
        run: ls -lrt
