name: Test Job
on:
  workflow_dispatch: {}


jobs:
  build:
    name: Build Project
    runs-on: ubuntu-18.04    
    steps:
            
        - name: rename test
          run: |
            mkdir riprasad-test
            ls -lrt
            mv ${{github.repository_owner}}* rename
            ls -lrt
          
