name: Test Job
on:
  workflow_dispatch: {}


jobs:
  build:
    name: Build Project
    runs-on: ubuntu-18.04    
    steps:
            
        - name: Fetch Apicurio Latest Release Metadata File
          run: echo "LATEST_RELEASE=$(curl https://api.github.com/repos/apicurio/apicurio-registry/releases/latest)" >> $GITHUB_ENV
          
        - name: Fetch Required Details from the Metadata File
          run: |
            echo "VERSION=$(echo ${LATEST_RELEASE} | jq '.tag_name' | sed 's/"//g')" >> >> $GITHUB_ENV
        
        - name: Test ${{ env.VERSION }}
          run: echo "${VERSION}"
