
name: Test Workflow
on:
  push:
    branches: [master, 1.2.x, 1.3.x]

jobs:
  test-push:
    name: Verify Build
    runs-on: ubuntu-18.04    
    steps:
      - name: Print Branch
        run: |
          echo "${{ github.ref }}"

      - name: Checkout Code With Ref '${{ github.ref }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: list directory
        run: ls -lrt
