name: Test Workflow

on:
  repository_dispatch:
    types: [abc]
  push:
    branches: [master]
  #pull_request:
  #  branches: [master]

#env:
#  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#  MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        run: docker pull quay.io/riprasad/koji-build-finder:1.0
      - name: Run Docker Image
        run: winpty docker run --entrypoint bash -it quay.io/riprasad/koji-build-finder:1.0
        
