
name: Test Workflow
on:
  push:
    branches: [master, '[1-9].[1-9].x']
  workflow_dispatch: {}

jobs:
  test-push:
    name: Test
    runs-on: ubuntu-18.04    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set Environment Variable
        run: echo "LATEST_COMMIT_SHA=$(git log -n 1 --pretty=format:"%H")" >> $GITHUB_ENV
      
      - name: print environment variable
        run: echo "$LATEST_COMMIT_SHA"
