
name: Test Notification
on:
  push:
    branches: [master, '[1-9].[1-9].x']
  workflow_dispatch: {}

jobs:
  test-push:
    name: Test
    runs-on: ubuntu-18.04    
    steps:
      
      - name: Print Message
        run: abc
        
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: ${{ failure() }}
