
name: Test Workflow
on:
  push:
    branches: [master, '[1-9].[1-9].x']

jobs:
  test-push:
    name: Verify Build
    runs-on: ubuntu-18.04    
    steps:
      - name: Print Branch
        run: |
          echo "${{ github.ref }}"
