
name: Test Notification
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version being released'
        required: true
      snapshot-version:
        description: 'Next snapshot version'
        required: true
      branch:
        description: 'Branch to release from'
        required: true
        default: 'master'

jobs:
  test-push:
    name: Test
    runs-on: ubuntu-18.04    
    steps:
      - name: Checkout Code With Ref '${{ github.ref }}'
        uses: actions/checkout@v2

      
      - name: Create GitHub Release
        run: |
          ./.github/scripts/create-github-release.sh ${{ github.event.inputs.release-version}} ${{ github.event.inputs.branch}} $GITHUB_REPOSITORY ${{ secrets.GITHUB_TOKEN }}
