name: Test Job
on:
  workflow_dispatch: {}


jobs:
  build:
    name: Build Project
    runs-on: ubuntu-18.04    
    steps:
            
    - name: Fetch required Details
      run: |
          touch latestRelease.json && curl https://api.github.com/repos/apicurio/apicurio-registry/releases/latest > latestRelease.json
          echo "RELEASE_VERSION=$(cat latestRelease.json | jq '.name' | sed 's/"//g')" >> $GITHUB_ENV
          echo "SOURCE_CODE_URL=$(cat latestRelease.json | jq '.zipball_url' | sed 's/"//g')" >> $GITHUB_ENV
          echo "BRANCH=$(cat latestRelease.json | jq '.target_commitish' | sed 's/"//g')" >> $GITHUB_ENV
        
    - name: Test ${{ env.RELEASE_VERSION }}
      run: |
        echo "${RELEASE_VERSION}"
        echo "${SOURCE_CODE_URL}"
        echo "${BRANCH}"
