#name: Verify Build Workflow
#on:
#  push:
#    branches: [master, 1.2.x, 2.0.x]

jobs:
  build-verify:
    name: Verify Build
    runs-on: ubuntu-18.04    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
            version: '8'
            architecture: x64
      - name: Apicurio Registry Checkout
        run: |
          mkdir registry
          cd registry
          git init
          git config --global user.name "apicurio-ci"
          git config --global user.email "apicurio.ci@gmail.com"
          git remote add origin "https://github.com/Apicurio/apicurio-registry.git"
          git fetch
          git pull origin master

      - name: Build Registry (All Variants)
        run: |
          cd registry
          mvn clean install -Pprod -Psql -Pinfinispan -Pstreams -Pasyncmem -Pkafkasql -DskipTests
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Login to DockerHub Registry
        if: github.event_name == 'push'
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build The Tagged Docker Images
        if: github.event_name == 'push'
        run: ./.github/scripts/build-snapshot-images-for-docker.sh ${{ github.ref }}

      - name: Tag Docker Images for dokerhub
        run: ./.github/scripts/tag-snapshot-images-for-docker.sh ${{ github.ref }}

      - name: List All The Tagged Docker Images
        if: github.event_name == 'push'
        run: docker images

      - name: Push The Tagged Docker Images To Dockerhub
        if: github.event_name == 'push'
        run: ./.github/scripts/push-snapshot-images-to-docker.sh ${{ github.ref }}

      - name: Login to Quay.io Registry
        if: github.event_name == 'push'
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Tag Docker Images for Quay.io
        if: github.event_name == 'push'
        run: ./.github/scripts/tag-snapshot-images-for-quay.sh ${{ github.ref }}
          
      - name: List All The Tagged Docker Images
        if: github.event_name == 'push'
        run: docker images

      - name: Push The Tagged Docker Images to Quay.io
        if: github.event_name == 'push'
        run: ./.github/scripts/push-snapshot-images-to-quay.sh ${{ github.ref }}
